(define (problem problema)
	(:domain domini)
	(:objects
		c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 - contingut
		dia10 dia9 dia8 dia7 dia6 dia5 dia4 dia3 dia2 dia1 - dia
	)
	(:init 
		(predecessor c1 c3)
		(predecessor c2 c3)
		(predecessor c3 c4)
        (predecessor c4 c5)
        (predecessor c5 c6)
        (predecessor c8 c9)
        (predecessor c9 c10)
         
        (paralel c6 c7)
         
		(dia-seguent dia1 dia2)
		(dia-seguent dia2 dia3)
		(dia-seguent dia3 dia4)
		(dia-seguent dia4 dia5)
		(dia-seguent dia5 dia6)
		(dia-seguent dia6 dia7)
		(dia-seguent dia7 dia8)
		(dia-seguent dia8 dia9)
		(dia-seguent dia9 dia10)

		(= (minutsVisionat c1) 80)
		(= (minutsVisionat c2) 120)
		(= (minutsVisionat c3) 70)
		(= (minutsVisionat c4) 90)
		(= (minutsVisionat c5) 100)
		(= (minutsVisionat c6) 80)
		(= (minutsVisionat c7) 90)
		(= (minutsVisionat c8) 110)
		(= (minutsVisionat c9) 120)
		(= (minutsVisionat c10) 80)

		(= (contingutsEnDia dia1) 0)
		(= (contingutsEnDia dia2) 0)
		(= (contingutsEnDia dia3) 0)
		(= (contingutsEnDia dia4) 0)
		(= (contingutsEnDia dia5) 0)
		(= (contingutsEnDia dia6) 0)
		(= (contingutsEnDia dia7) 0)
		(= (contingutsEnDia dia8) 0)
		(= (contingutsEnDia dia9) 0)
		(= (contingutsEnDia dia10) 0)

		(= (minutsEnDia dia1) 0)
		(= (minutsEnDia dia2) 0)
		(= (minutsEnDia dia3) 0)
		(= (minutsEnDia dia4) 0)
		(= (minutsEnDia dia5) 0)
		(= (minutsEnDia dia6) 0)
		(= (minutsEnDia dia7) 0)
		(= (minutsEnDia dia8) 0)
		(= (minutsEnDia dia9) 0)
		(= (minutsEnDia dia10) 0)
    )
        
	(:goal (and (continguts-vistos c1) 
				(continguts-vistos c2) 
				(continguts-vistos c3) 
				(continguts-vistos c4) 
				(continguts-vistos c5) 
				(continguts-vistos c6) 
				(continguts-vistos c7) 
				(continguts-vistos c8)
				(continguts-vistos c9)
				(continguts-vistos c10)))

)