(define (problem problema3)
   (:domain domini)
   (:objects
      cont1 cont2 cont3 cont4 cont5 cont6 cont7 cont8 cont9 cont10 cont11 cont12 cont13 cont14 cont15 - contingut
      dia1 dia2 dia3 dia4 dia5 dia6 dia7 dia8 dia9 dia10 - dia
   )
   (:init
      (predecessor cont11 cont15 )
      (predecessor cont3 cont7 )
      (predecessor cont8 cont10 )
      (predecessor cont1 cont3 )
      (predecessor cont14 cont12 )
      (predecessor cont14 cont2 )
      (predecessor cont7 cont8 )
      (predecessor cont2 cont5 )
      (predecessor cont14 cont6 )
      (paralel cont5 cont13 )
      (paralel cont10 cont15 )
      (paralel cont6 cont12 )
      (paralel cont4 cont10 )
      (= ( minutsVisionat cont1 ) 150 )
      (= ( minutsVisionat cont2 ) 165 )
      (= ( minutsVisionat cont3 ) 110 )
      (= ( minutsVisionat cont4 ) 90 )
      (= ( minutsVisionat cont5 ) 25 )
      (= ( minutsVisionat cont6 ) 165 )
      (= ( minutsVisionat cont7 ) 150 )
      (= ( minutsVisionat cont8 ) 110 )
      (= ( minutsVisionat cont9 ) 35 )
      (= ( minutsVisionat cont10 ) 30 )
      (= ( minutsVisionat cont11 ) 30 )
      (= ( minutsVisionat cont12 ) 25 )
      (= ( minutsVisionat cont13 ) 140 )
      (= ( minutsVisionat cont14 ) 170 )
      (= ( minutsVisionat cont15 ) 85 )
      (dia-seguent dia1 dia2 )
      (dia-seguent dia1 dia3 )
      (dia-seguent dia1 dia4 )
      (dia-seguent dia1 dia5 )
      (dia-seguent dia1 dia6 )
      (dia-seguent dia1 dia7 )
      (dia-seguent dia1 dia8 )
      (dia-seguent dia1 dia9 )
      (dia-seguent dia1 dia10 )
      (dia-seguent dia2 dia3 )
      (dia-seguent dia2 dia4 )
      (dia-seguent dia2 dia5 )
      (dia-seguent dia2 dia6 )
      (dia-seguent dia2 dia7 )
      (dia-seguent dia2 dia8 )
      (dia-seguent dia2 dia9 )
      (dia-seguent dia2 dia10 )
      (dia-seguent dia3 dia4 )
      (dia-seguent dia3 dia5 )
      (dia-seguent dia3 dia6 )
      (dia-seguent dia3 dia7 )
      (dia-seguent dia3 dia8 )
      (dia-seguent dia3 dia9 )
      (dia-seguent dia3 dia10 )
      (dia-seguent dia4 dia5 )
      (dia-seguent dia4 dia6 )
      (dia-seguent dia4 dia7 )
      (dia-seguent dia4 dia8 )
      (dia-seguent dia4 dia9 )
      (dia-seguent dia4 dia10 )
      (dia-seguent dia5 dia6 )
      (dia-seguent dia5 dia7 )
      (dia-seguent dia5 dia8 )
      (dia-seguent dia5 dia9 )
      (dia-seguent dia5 dia10 )
      (dia-seguent dia6 dia7 )
      (dia-seguent dia6 dia8 )
      (dia-seguent dia6 dia9 )
      (dia-seguent dia6 dia10 )
      (dia-seguent dia7 dia8 )
      (dia-seguent dia7 dia9 )
      (dia-seguent dia7 dia10 )
      (dia-seguent dia8 dia9 )
      (dia-seguent dia8 dia10 )
      (dia-seguent dia9 dia10 )
      (= ( contingutsEnDia dia1 ) 0 )
      (= ( minutsEnDia dia1 ) 0 )
      (= ( contingutsEnDia dia2 ) 0 )
      (= ( minutsEnDia dia2 ) 0 )
      (= ( contingutsEnDia dia3 ) 0 )
      (= ( minutsEnDia dia3 ) 0 )
      (= ( contingutsEnDia dia4 ) 0 )
      (= ( minutsEnDia dia4 ) 0 )
      (= ( contingutsEnDia dia5 ) 0 )
      (= ( minutsEnDia dia5 ) 0 )
      (= ( contingutsEnDia dia6 ) 0 )
      (= ( minutsEnDia dia6 ) 0 )
      (= ( contingutsEnDia dia7 ) 0 )
      (= ( minutsEnDia dia7 ) 0 )
      (= ( contingutsEnDia dia8 ) 0 )
      (= ( minutsEnDia dia8 ) 0 )
      (= ( contingutsEnDia dia9 ) 0 )
      (= ( minutsEnDia dia9 ) 0 )
      (= ( contingutsEnDia dia10 ) 0 )
      (= ( minutsEnDia dia10 ) 0 )
      ; (continguts-vistos cont2 )
      ; (continguts-vistos cont7 )
      ; (continguts-vistos cont1 )
   )
   (:goal (and
      (continguts-vistos cont5 )
      (continguts-vistos cont14 )
   ))
)