(define (problem problema2)
   (:domain domini)
   (:objects
      cont1 cont2 cont3 cont4 cont5 cont6 cont7 cont8 cont9 cont10 cont11 cont12 cont13 cont14 cont15 - contingut
      dia1 dia2 dia3 dia4 dia5 dia6 dia7 dia8 dia9 dia10 dia11 dia12 - dia
   )
   (:init
      (predecessor cont13 cont1 )
      (predecessor cont6 cont10 )
      (predecessor cont3 cont14 )
      (predecessor cont2 cont10 )
      (predecessor cont2 cont8 )
      (predecessor cont9 cont11 )
      (predecessor cont4 cont7 )
      (predecessor cont9 cont5 )
      (predecessor cont8 cont6 )
      (predecessor cont9 cont6 )
      (predecessor cont11 cont1 )
      (predecessor cont14 cont7 )
      (predecessor cont14 cont1 )
      (predecessor cont2 cont9 )
      (paralel cont10 cont12 )
      (paralel cont1 cont15 )
      (= ( minutsVisionat cont1 ) 85 )
      (= ( minutsVisionat cont2 ) 50 )
      (= ( minutsVisionat cont3 ) 150 )
      (= ( minutsVisionat cont4 ) 175 )
      (= ( minutsVisionat cont5 ) 25 )
      (= ( minutsVisionat cont6 ) 175 )
      (= ( minutsVisionat cont7 ) 25 )
      (= ( minutsVisionat cont8 ) 40 )
      (= ( minutsVisionat cont9 ) 65 )
      (= ( minutsVisionat cont10 ) 65 )
      (= ( minutsVisionat cont11 ) 70 )
      (= ( minutsVisionat cont12 ) 130 )
      (= ( minutsVisionat cont13 ) 105 )
      (= ( minutsVisionat cont14 ) 150 )
      (= ( minutsVisionat cont15 ) 140 )
      (dia-seguent dia1 dia2 )
      (dia-seguent dia1 dia3 )
      (dia-seguent dia1 dia4 )
      (dia-seguent dia1 dia5 )
      (dia-seguent dia1 dia6 )
      (dia-seguent dia1 dia7 )
      (dia-seguent dia1 dia8 )
      (dia-seguent dia1 dia9 )
      (dia-seguent dia1 dia10 )
      (dia-seguent dia1 dia11 )
      (dia-seguent dia1 dia12 )
      (dia-seguent dia2 dia3 )
      (dia-seguent dia2 dia4 )
      (dia-seguent dia2 dia5 )
      (dia-seguent dia2 dia6 )
      (dia-seguent dia2 dia7 )
      (dia-seguent dia2 dia8 )
      (dia-seguent dia2 dia9 )
      (dia-seguent dia2 dia10 )
      (dia-seguent dia2 dia11 )
      (dia-seguent dia2 dia12 )
      (dia-seguent dia3 dia4 )
      (dia-seguent dia3 dia5 )
      (dia-seguent dia3 dia6 )
      (dia-seguent dia3 dia7 )
      (dia-seguent dia3 dia8 )
      (dia-seguent dia3 dia9 )
      (dia-seguent dia3 dia10 )
      (dia-seguent dia3 dia11 )
      (dia-seguent dia3 dia12 )
      (dia-seguent dia4 dia5 )
      (dia-seguent dia4 dia6 )
      (dia-seguent dia4 dia7 )
      (dia-seguent dia4 dia8 )
      (dia-seguent dia4 dia9 )
      (dia-seguent dia4 dia10 )
      (dia-seguent dia4 dia11 )
      (dia-seguent dia4 dia12 )
      (dia-seguent dia5 dia6 )
      (dia-seguent dia5 dia7 )
      (dia-seguent dia5 dia8 )
      (dia-seguent dia5 dia9 )
      (dia-seguent dia5 dia10 )
      (dia-seguent dia5 dia11 )
      (dia-seguent dia5 dia12 )
      (dia-seguent dia6 dia7 )
      (dia-seguent dia6 dia8 )
      (dia-seguent dia6 dia9 )
      (dia-seguent dia6 dia10 )
      (dia-seguent dia6 dia11 )
      (dia-seguent dia6 dia12 )
      (dia-seguent dia7 dia8 )
      (dia-seguent dia7 dia9 )
      (dia-seguent dia7 dia10 )
      (dia-seguent dia7 dia11 )
      (dia-seguent dia7 dia12 )
      (dia-seguent dia8 dia9 )
      (dia-seguent dia8 dia10 )
      (dia-seguent dia8 dia11 )
      (dia-seguent dia8 dia12 )
      (dia-seguent dia9 dia10 )
      (dia-seguent dia9 dia11 )
      (dia-seguent dia9 dia12 )
      (dia-seguent dia10 dia11 )
      (dia-seguent dia10 dia12 )
      (dia-seguent dia11 dia12 )
      (= ( contingutsEnDia dia1 ) 0 )
      (= ( minutsEnDia dia1 ) 0 )
      (= ( contingutsEnDia dia2 ) 0 )
      (= ( minutsEnDia dia2 ) 0 )
      (= ( contingutsEnDia dia3 ) 0 )
      (= ( minutsEnDia dia3 ) 0 )
      (= ( contingutsEnDia dia4 ) 0 )
      (= ( minutsEnDia dia4 ) 0 )
      (= ( contingutsEnDia dia5 ) 0 )
      (= ( minutsEnDia dia5 ) 0 )
      (= ( contingutsEnDia dia6 ) 0 )
      (= ( minutsEnDia dia6 ) 0 )
      (= ( contingutsEnDia dia7 ) 0 )
      (= ( minutsEnDia dia7 ) 0 )
      (= ( contingutsEnDia dia8 ) 0 )
      (= ( minutsEnDia dia8 ) 0 )
      (= ( contingutsEnDia dia9 ) 0 )
      (= ( minutsEnDia dia9 ) 0 )
      (= ( contingutsEnDia dia10 ) 0 )
      (= ( minutsEnDia dia10 ) 0 )
      (= ( contingutsEnDia dia11 ) 0 )
      (= ( minutsEnDia dia11 ) 0 )
      (= ( contingutsEnDia dia12 ) 0 )
      (= ( minutsEnDia dia12 ) 0 )
      ; (continguts-vistos cont7 )
      ; (continguts-vistos cont6 )
      ; (continguts-vistos cont4 )
      ; (continguts-vistos cont11 )
   )
   (:goal (and
      (continguts-vistos cont10 )
      (continguts-vistos cont5 )
   ))
)