(define (problem problema3)
   (:domain domini)
   (:objects
      cont1 cont2 cont3 cont4 cont5 cont6 cont7 cont8 cont9 cont10 cont11 cont12 cont13 cont14 cont15 - contingut
      dia1 dia2 dia3 dia4 dia5 dia6 dia7 dia8 dia9 dia10 - dia
   )
   (:init
      (predecessor cont2 cont13 )
      (predecessor cont13 cont4 )
      (predecessor cont12 cont10 )
      (predecessor cont8 cont6 )
      (predecessor cont3 cont10 )
      (predecessor cont14 cont1 )
      (predecessor cont5 cont8 )
      (predecessor cont2 cont3 )
      (predecessor cont2 cont10 )
      (predecessor cont2 cont15 )
      (predecessor cont6 cont4 )
      (predecessor cont9 cont12 )
      (predecessor cont3 cont6 )
      (predecessor cont1 cont12 )
      (paralel cont10 cont4 )
      (dia-seguent dia1 dia2 )
      (dia-seguent dia1 dia3 )
      (dia-seguent dia1 dia4 )
      (dia-seguent dia1 dia5 )
      (dia-seguent dia1 dia6 )
      (dia-seguent dia1 dia7 )
      (dia-seguent dia1 dia8 )
      (dia-seguent dia1 dia9 )
      (dia-seguent dia1 dia10 )
      (dia-seguent dia2 dia3 )
      (dia-seguent dia2 dia4 )
      (dia-seguent dia2 dia5 )
      (dia-seguent dia2 dia6 )
      (dia-seguent dia2 dia7 )
      (dia-seguent dia2 dia8 )
      (dia-seguent dia2 dia9 )
      (dia-seguent dia2 dia10 )
      (dia-seguent dia3 dia4 )
      (dia-seguent dia3 dia5 )
      (dia-seguent dia3 dia6 )
      (dia-seguent dia3 dia7 )
      (dia-seguent dia3 dia8 )
      (dia-seguent dia3 dia9 )
      (dia-seguent dia3 dia10 )
      (dia-seguent dia4 dia5 )
      (dia-seguent dia4 dia6 )
      (dia-seguent dia4 dia7 )
      (dia-seguent dia4 dia8 )
      (dia-seguent dia4 dia9 )
      (dia-seguent dia4 dia10 )
      (dia-seguent dia5 dia6 )
      (dia-seguent dia5 dia7 )
      (dia-seguent dia5 dia8 )
      (dia-seguent dia5 dia9 )
      (dia-seguent dia5 dia10 )
      (dia-seguent dia6 dia7 )
      (dia-seguent dia6 dia8 )
      (dia-seguent dia6 dia9 )
      (dia-seguent dia6 dia10 )
      (dia-seguent dia7 dia8 )
      (dia-seguent dia7 dia9 )
      (dia-seguent dia7 dia10 )
      (dia-seguent dia8 dia9 )
      (dia-seguent dia8 dia10 )
      (dia-seguent dia9 dia10 )
      (assignacions-3 dia1 )
      (assignacions-3 dia2 )
      (assignacions-3 dia3 )
      (assignacions-3 dia4 )
      (assignacions-3 dia5 )
      (assignacions-3 dia6 )
      (assignacions-3 dia7 )
      (assignacions-3 dia8 )
      (assignacions-3 dia9 )
      (assignacions-3 dia10 )
      ; (continguts-vistos cont12 )
      ; (continguts-vistos cont8 )
      ; (continguts-vistos cont4 )
      ; (continguts-vistos cont7 )
      ; (continguts-vistos cont11 )
   )
   (:goal (and
      (continguts-vistos cont10 )
      (continguts-vistos cont9 )
      (continguts-vistos cont2 )
   ))
)