(define (problem problema2)
   (:domain domini)
   (:objects
      cont1 cont2 cont3 cont4 cont5 cont6 cont7 cont8 cont9 cont10 - contingut
      dia1 dia2 dia3 dia4 dia5 dia6 dia7 dia8 dia9 dia10 - dia
   )
   (:init
      (predecessor cont2 cont5 )
      (predecessor cont6 cont3 )
      (predecessor cont7 cont5 )
      (predecessor cont10 cont1 )
      (predecessor cont8 cont9 )
      (predecessor cont7 cont3 )
      (predecessor cont2 cont4 )
      (predecessor cont4 cont3 )
      (predecessor cont4 cont5 )
      (predecessor cont10 cont2 )
      (paralel cont1 cont5 )
      (paralel cont1 cont3 )
      (dia-seguent dia1 dia2 )
      (dia-seguent dia1 dia3 )
      (dia-seguent dia1 dia4 )
      (dia-seguent dia1 dia5 )
      (dia-seguent dia1 dia6 )
      (dia-seguent dia1 dia7 )
      (dia-seguent dia1 dia8 )
      (dia-seguent dia1 dia9 )
      (dia-seguent dia1 dia10 )
      (dia-seguent dia2 dia3 )
      (dia-seguent dia2 dia4 )
      (dia-seguent dia2 dia5 )
      (dia-seguent dia2 dia6 )
      (dia-seguent dia2 dia7 )
      (dia-seguent dia2 dia8 )
      (dia-seguent dia2 dia9 )
      (dia-seguent dia2 dia10 )
      (dia-seguent dia3 dia4 )
      (dia-seguent dia3 dia5 )
      (dia-seguent dia3 dia6 )
      (dia-seguent dia3 dia7 )
      (dia-seguent dia3 dia8 )
      (dia-seguent dia3 dia9 )
      (dia-seguent dia3 dia10 )
      (dia-seguent dia4 dia5 )
      (dia-seguent dia4 dia6 )
      (dia-seguent dia4 dia7 )
      (dia-seguent dia4 dia8 )
      (dia-seguent dia4 dia9 )
      (dia-seguent dia4 dia10 )
      (dia-seguent dia5 dia6 )
      (dia-seguent dia5 dia7 )
      (dia-seguent dia5 dia8 )
      (dia-seguent dia5 dia9 )
      (dia-seguent dia5 dia10 )
      (dia-seguent dia6 dia7 )
      (dia-seguent dia6 dia8 )
      (dia-seguent dia6 dia9 )
      (dia-seguent dia6 dia10 )
      (dia-seguent dia7 dia8 )
      (dia-seguent dia7 dia9 )
      (dia-seguent dia7 dia10 )
      (dia-seguent dia8 dia9 )
      (dia-seguent dia8 dia10 )
      (dia-seguent dia9 dia10 )
      (assignacions-3 dia1 )
      (assignacions-3 dia2 )
      (assignacions-3 dia3 )
      (assignacions-3 dia4 )
      (assignacions-3 dia5 )
      (assignacions-3 dia6 )
      (assignacions-3 dia7 )
      (assignacions-3 dia8 )
      (assignacions-3 dia9 )
      (assignacions-3 dia10 )
   )
   (:goal (and
      (continguts-vistos cont1)
      (continguts-vistos cont10 )
      (continguts-vistos cont9 )
   ))
)