(define (problem prob1)
   (:domain domini)
   (:objects
      cont1 cont2 cont3 cont4 cont5 cont6 cont7 cont8 cont9 - contingut
      dia1 dia2 dia3 dia4 dia5 dia6 dia7 dia8 dia9 dia10 - dia
   )
   (:init
      (predecessor cont5 cont9 )
      (predecessor cont2 cont9 )
      (predecessor cont7 cont5 )
      (paralel cont6 cont7 )
      (paralel cont8 cont9 )
      (paralel cont8 cont4 )
      (dia-seguent dia1 dia2 )
      (dia-seguent dia1 dia3 )
      (dia-seguent dia1 dia4 )
      (dia-seguent dia1 dia5 )
      (dia-seguent dia1 dia6 )
      (dia-seguent dia1 dia7 )
      (dia-seguent dia1 dia8 )
      (dia-seguent dia1 dia9 )
      (dia-seguent dia1 dia10 )
      (dia-seguent dia2 dia3 )
      (dia-seguent dia2 dia4 )
      (dia-seguent dia2 dia5 )
      (dia-seguent dia2 dia6 )
      (dia-seguent dia2 dia7 )
      (dia-seguent dia2 dia8 )
      (dia-seguent dia2 dia9 )
      (dia-seguent dia2 dia10 )
      (dia-seguent dia3 dia4 )
      (dia-seguent dia3 dia5 )
      (dia-seguent dia3 dia6 )
      (dia-seguent dia3 dia7 )
      (dia-seguent dia3 dia8 )
      (dia-seguent dia3 dia9 )
      (dia-seguent dia3 dia10 )
      (dia-seguent dia4 dia5 )
      (dia-seguent dia4 dia6 )
      (dia-seguent dia4 dia7 )
      (dia-seguent dia4 dia8 )
      (dia-seguent dia4 dia9 )
      (dia-seguent dia4 dia10 )
      (dia-seguent dia5 dia6 )
      (dia-seguent dia5 dia7 )
      (dia-seguent dia5 dia8 )
      (dia-seguent dia5 dia9 )
      (dia-seguent dia5 dia10 )
      (dia-seguent dia6 dia7 )
      (dia-seguent dia6 dia8 )
      (dia-seguent dia6 dia9 )
      (dia-seguent dia6 dia10 )
      (dia-seguent dia7 dia8 )
      (dia-seguent dia7 dia9 )
      (dia-seguent dia7 dia10 )
      (dia-seguent dia8 dia9 )
      (dia-seguent dia8 dia10 )
      (dia-seguent dia9 dia10 )
      (dies-consecutius dia1 dia2 )
      (dies-consecutius dia2 dia3 )
      (dies-consecutius dia3 dia4 )
      (dies-consecutius dia4 dia5 )
      (dies-consecutius dia5 dia6 )
      (dies-consecutius dia6 dia7 )
      (dies-consecutius dia7 dia8 )
      (dies-consecutius dia8 dia9 )
      (dies-consecutius dia9 dia10 )
      ;(continguts-vistos cont6 )
   )
   (:goal (and
      (continguts-vistos cont5 )
      (continguts-vistos cont8 )
   ))
)